### ISSUE TITLE
npm package name

### ISSUE THREAD

**Issue by neilstuartcraig** [mcollina/my-ua-parser#1]
Hey @mcollina and thanks for forking this and raising the license issue - that matters for our use case so I am migrating.

I just noticed whilst migrating that the [readme still says `npm install ua-parser-js`](https://github.com/mcollina/my-ua-parser/tree/main?tab=readme-ov-file#using-nodejs) which is the original package name.

If it's OK, i'll have a hunt through and create a PR to update this and any others I find.

Cheers, Neil. 🙌🏻

**Comment by mcollina** [comment]
Thanks, that would be amazing! I did a very quick fork.

**Comment by neilstuartcraig** [comment]
No worries, I'll do that as soon as I get a moment.

**Comment by neilstuartcraig** [comment]
Migration was really quick so I am on this now. 

Do you want me to update/remove [the TypeScript section of the main readme](https://github.com/mcollina/my-ua-parser?tab=readme-ov-file#using-typescript)? I don't use TS myself so am not familiar but it references the original package and I couldn't find an `@type` package for the fork (presumably that needs extra wiring):

```
$ npm install --save @types/ua-parser-js
# Download TS type definition from DefinitelyTyped repository:
# https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/ua-parser-js
```

**Comment by mcollina** [comment]
There should be no need for that section at all. I pulled the types directly in the package https://github.com/mcollina/my-ua-parser/blob/main/ua-parser.d.ts

**Comment by neilstuartcraig** [comment]
Perfect, thanks, I'll remove it then.

**Comment by neilstuartcraig** [comment]
Sorry to keep message but I also noticed that the link for ["This fork was done at [commit](https://github.com/mcollina/my-ua-parser/blob/main/693a83de2e4cf8384f43f6a5831e58663c572580)."](https://github.com/mcollina/my-ua-parser?tab=readme-ov-file#credits) 404s. GitHub seems to get the path wrong (`/blob/main/` but I think it should be `/commit/` - not sure how to fix that).

And I think I need permission to push to this repo as I get this:
```
git push origin update-package-name-in-docs
remote: Permission to mcollina/my-ua-parser.git denied to neilstuartcraig.
fatal: unable to access 'https://github.com/mcollina/my-ua-parser/': The requested URL returned error: 403
```

Any chance you can grant me sufficient permissions to push please? (or let me know if you prefer me to create a fork in my account perhaps).

**Comment by mcollina** [comment]
You can send a pull request instead?

**Comment by xfournet** [comment]
PR #3 created
