### ISSUE TITLE
Question about my-ua-parser

### ISSUE THREAD

**Issue by LikhonX** [mcollina/my-ua-parser#2]
Hey there! 👋 Your project my-ua-parser caught my eye on the trending list. Incredible job! 💪 Could you share what the most rewarding part of developing this project was? Looking forward to your insights!

Best regards,
@nectariferous
Telegram: [t.me/nectariferous](https://t.me/nectariferous)

- 🌐 Web: [likhon.xyz](https://likhon.xyz)
© All rights reserved.

👉 For Promo/Help/Support, DM [@nectariferous](https://t.me/likhondotxyz)

**Comment by mcollina** [comment]
You can read the motivation at https://adventures.nodeland.dev/archive/what-happens-when-a-major-npm-library-goes/
